# Generated by Django 5.1.3 on 2024-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='poster_path',
            field=models.URLField(default='/default-poster.png'),
        ),
    ]
