# Generated by Django 5.1.3 on 2024-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_alter_series_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
