# Generated by Django 5.1.3 on 2024-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_alter_movie_description_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='series',
            field=models.ManyToManyField(related_name='playlists', to='streaming.series'),
        ),
    ]
